language: python

python:
  - "2.7"
  - "2.6"

install:
  - "pip install -r requirements.txt"
  - "pip install pymongo"
  - "pip install pysqlite sqlalchemy alembic"

services:
  - mongodb

script: nosetests
